version: '2'

services:
  scorebot:
    build: .
    restart: unless-stopped
    volumes:
      - scorebot-data:/usr/src/app/data
    environment:
      - BOT_TOKEN=5207172086:AAFiTVrYgWOL-0MVKh_Wk8I1C3sb5ZSXBwo

volumes:
  scorebot-data:
